# Generated by Django 3.0.3 on 2020-02-22 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='magiccard',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='magicset',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
